name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Build and Publish Docker image
      uses: Kolkies/githubpackages-docker@v1.0.4
      with:
        repo-token: ${{ secrets.GH_TOKEN }}
        image-name: node-nats

